// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".
#define IDR_ICO_MAIN  8001
#define razgruzka  		1001
#define mainform  		1002
#define goodslist  		1003
#define nasklad  		1004
#define options  		1005
#define Login  			1006
#define treeview  		1007
#define pogruzka  		1008
#define documentlist  	1009
#define viborzadaniya   1010
#define upakovka  		1011
#define GoodsTree  		1012
#define VvodForm  		1013
#define ErrorForm  		1014
#define InfoForm  		1015
#define Razgrfrm		1016
#define Voprosfrm		1017
#define scanfrm			1018
#define DefragForm  	1019



#define popupmenu  2001
#define menuitem1  6001
#define Sound2  	8002
#define Sound3  	8003

#define list  		4001
#define combo  		4002
#define PortEdit    4006
#define Namespace   4008
#define Userlist    4004
#define password    4007
#define treelist    4005
#define scancode    4021
#define sledfilial  4020
#define noscan      4022
#define ServerName  4003
#define zakonchit   4023
#define ErrorMsg    4009
#define transport    4024

#define tab1  4010
#define VersionNumber  4012
